[package]
name = "too-many-timestamps"
version = "0.1.0"
authors = ["0x5c <dev@0x5c.io>"]
edition = "2018"

[[bin]]
name = "timestamps"
path = "src/timestamps.rs"

[dependencies]
chrono = "0.4"
clap = "2.33.3"
crossterm = "0.20.0"
